/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [
    {
      type: 'doc',
      label: 'Documentation',
      id: 'index',
    },
    {
      type: 'category',
      label: 'Core',
      link: {
        type: 'generated-index',
        title: 'Ox Core',
        description: 'An experimental framework for FiveM. Limited support and breaking changes guaranteed.',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'ox_core',
        },
      ],
    },
    {
      type: 'category',
      label: 'MySQL',
      items: [
        {
          type: 'autogenerated',
          dirName: 'oxmysql',
        },
      ],
    },
    {
      type: 'category',
      label: 'Library',
      items: [
        {
          type: 'autogenerated',
          dirName: 'ox_lib',
        },
      ],
    },
    {
      type: 'category',
      label: 'Inventory',
      items: [
        {
          type: 'autogenerated',
          dirName: 'ox_inventory',
        },
      ],
    },
  ],
};

module.exports = sidebars;
